language: ruby
bundler_args: --without development
cache: bundler
rvm:
  - 2.0.0
before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare
script:
  - bundle exec rspec
notifications:
  email:
    recipients:
      - vinialm88@gmail.com
addons:
  code_climate:
    repo_token: 4552d22317d8c99d6213c2b3d822008078def88233bd601b53b63f7d70f66ef9
